SOURCES=$(wildcard *.cpp)
TESTSOURCES=$(wildcard test/*.cpp)
LIBRARY=libmain.a
PROJECTROOT=..
TESTDEPLIBS=
LIBDEPLIBS=$(SRCROOT)/ui/libtextui.a $(SRCROOT)/bridge/libbridge.a $(SRCROOT)/viewmodel/libviewmodel.a

include $(PROJECTROOT)/Make.rules
